version: "3.5"
services:
  mariadb:
    image: mariadb:10.5
    networks:
      - dev-net
    restart: on-failure
    volumes:
      - data-mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mydb
      MYSQL_USER: mariadb-user
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"

networks:
  dev-net:
    name: dev-net
    driver: bridge
volumes:
  data-mariadb:
    name: data-mariadb
